### ISSUE TITLE
UI Feedback

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/prioritize#3]
I'm aware you're aware it's barebones. I figured I would list out the things I would want to see or do that I can't.

- [x] Tell me the last time I did it. This could/should be pretty small print, but it'd be nice to know.
- [x] Make a tab or hide/unhide to view ones that aren't currently due-ish. I may want to delete one (I did a test one that is now vanished to the ether for 30 days), or I may have, for some reason, done a task earlier than required, and want to reset the clock.

And I love your minimal phone friendly UIs. (YATA is probably the only Sandstorm app I use via mobile web.) But I would probably:

- [x] Decrease spacing between lines representing the same task.
- [x] *Maybe* put a box around each, but I'm not devoted to the idea.

**Comment by zenhack** [comment]
Yeah, a lot of these have occurred to me, but it's definitely worth recording them.

Mobile friendly styling is surprisingly easy: prioritize literally does not have a stylesheet :P.

**Comment by ocdtrekkie** [comment]
Actually, can we add one mobile styling fix that should feel familiar: https://github.com/zenhack/yata/commit/7a8815c79fa4b7b1d657c9ab05d7c0d4566989a8

**Comment by zenhack** [comment]
These are now all done (including the font size issue); they will be in the next release. Closing.

**Comment by zenhack** [comment]
These and the fix for #4 are now included in the spk at:

https://mirror.zenhack.net/pub/prioritize.spk

I still want to fix #1 and #2 before submitting this to the app market.

**Comment by ocdtrekkie** [comment]
Delightful! Thank you!
