### ISSUE TITLE
Round times to days (internally)

### ISSUE THREAD

**Issue by zenhack** [zenhack/prioritize#4]
For expediency, the current implementation just stores the times things are "done" as unix timestamps -- to the millisecond. This is mostly fine, but it means the check for "is this overdue" will say no if something is due every 2 days, and you did it 2 days ago in the evening but it's afternoon now. This is not really what I want; we should clamp things to days so that if it's the same day it counts. This gets a little fiddly since you have to start worrying about timezones, which is why I didn't tackle it up front, but we should fix it at some point.

**Comment by ocdtrekkie** [comment]
I was thinking about this deadline-slippage issue, but I wasn't sure if you intended this to be used on tasks that were so tied to specific days or not. I have a task to check if my backups are good regularly: If this slips a day, I do not care, and the functionality is fine as-is.

However, if I have a task to do a monthly report that needs to be done somewhere in the last week of the month, deadline-slippage could be occasionally irritating: Eventually it will end up at the start of the next month. I was almost wondering if you could bad-hack this by dropping 8 or 12 hours from the period of every task, so they're roughly still the right length of time, but can accommodate some ability to slip backwards as well as forwards.

**Comment by zenhack** [comment]
Most of the things I use this for are not that sensitive, but I do want
to think on day-granularity.

In particular, I have some tasks that in theory should happen every day,
so they should basically always be on the list, but move to the top if
I've not been keeping up. But for such short term tasks the slippage can
essentially turn it into an every-2 instead of every-1, which is
significant.

Quoting Jacob Weisz (2021-12-03 15:01:27)

> I was almost wondering if you could bad-hack this [...]

The correct solution is not actually very hard: I just need to round
timestamps down to the start of the day across the board. This way two
times on the same day will be seen as equal. This ticket is mostly a
reminder to myself; there's not a lot to figure out here I think.
