### ISSUE TITLE
Last done and rounded days does a weird thing

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/prioritize#5]
Not really a significant issue persay (doesn't actually bother me or impact my usage meaningfully... really), but your change to day behavior can create a weird look when this appears due:

![image](https://user-images.githubusercontent.com/4399499/147147719-a89941d6-82aa-4bde-bea0-05761eaba6b2.png)

**Comment by zenhack** [comment]
Hm. Can you extract the entry from grain storage so I can look at the exact timestamps? There's just a json file in /var, it should be easy to pull it out and scrub other items.

**Comment by ocdtrekkie** [comment]
`{"k":8,"v":{"title":"Clean Mortimer's tank","period":1209600000,"lastDone":1639012433536}}`

Here you go.

**Comment by zenhack** [comment]
Should be fixed. Problem was I was doing the rounding when sorting & filtering, but not when displaying. Spk is updated.
