### ISSUE TITLE
Icons, screenshots, other package metadata.

### ISSUE THREAD

**Issue by zenhack** [zenhack/prioritize#7]
This is really all that's left before I'd say this is ready for the app market.

**Comment by ocdtrekkie** [comment]
Prioritize icon as a search has some neat suggestions for the icon. I like the idea of showing a task item getting moved around to a different spot: https://duckduckgo.com/?q=prioritize+icon&t=iphone&iar=images&iax=images&ia=images

**Comment by zenhack** [comment]
Yeah, I like that too. I made a first pass, there's now an icon.svg in the repo, though I haven't hooked it up to the pkgdef yet, and I will probably want to change things once I see what it looks like in the UI.

**Comment by zenhack** [comment]
All this is done, I've tagged 0.1 and pushed it to the market. Closing.
